name: "CI: Build and Push LightMessagesBackend Docker Image"

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    name: Build and Push Docker Image
    # Only run this job if the commit message contains 'build-docker-image'
    if: ${{ contains(github.event.head_commit.message, 'build-docker-image') }}
    # GitHub-hosted runner
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Set up Docker Buildx for advanced builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 4: Build and push the image
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: docker/production/Dockerfile  # Path to your Dockerfile
          push: true
          tags: |
            abdelslam1997/light_messages_frontend:latest
            abdelslam1997/light_messages_frontend:v1.0.${{ github.run_number }}

      # Step 5: Verify Image Build
      - name: Verify Docker Image
        run: docker pull abdelslam1997/light_messages_frontend:latest
